### ISSUE TITLE
Mandates need a cancel method (and maybe update method too)

### ISSUE THREAD

**Issue by grifferz** [Humanstate/business-gocardless#12]
The Mandate class needs a cancel method.

I tried:

``
$mandate->_operation('actions/cancel', 'api_post');
``

which did appear to produce the desired result although did produce a warning:

```
Use of uninitialized value $_ in concatenation (.) or string at … Business/GoCardless/Resource.pm line 119.
```

so perhaps other changes are needed in the Resource class?

The only other unrestricted endpoint not yet implemented for mandates is "update" for updating the metadata: https://developer.gocardless.com/api-reference/#mandates-update-a-mandate

**Comment by leejo** [comment]
v0.30 on its way to CPAN, which adds the `->cancel`, `->update`, and various status check methods to the Mandate class. Ta!
