### ISSUE TITLE
"Error 411 (Length Required)!!1" on mandate cancellation

### ISSUE THREAD

**Issue by grifferz** [Humanstate/business-gocardless#13]
At some point between 25 October, when my last mandate->cancel happened, and yesterday, Google App Engine appears to have tightened its requirements such that POST requests without a Content-Length header are rejected with a 411 before they even reach api.gocardless.com.

Requests like mandate->cancel don't send a POST body and it seems that LWP does not send a Content-Length header in that case.

For now I hacked a fix together by adding:

    $req->header( 'Content-Length' => 0 ) unless $json;

at line 372 of lib/Business/GoCardless/Client.pm.

I haven't yet looked into whether LWP is the one at fault here (if Content-Length is always required on a POST, by the standard).

(And yes, they do seem to have put "!!1" at the end of their error title…)

**Comment by leejo** [comment]
I think the RFCs have always said the Content-Length *SHOULD* be included, so it's not a *MUST*. It seems odd that this would be changed to be a requirement as i'm pretty sure it would break loads of client code. Can you track down a definitive change log for this?

**Comment by grifferz** [comment]
I cannot find anything, but:

* Someone tells me that they worked at GoCardless back in June/July and at that time GC was planning to move things into Google's cloud
* There's tons of results all over the web of that error message ("POST requests require a Content-length header. That’s all we know.") from people trying to interact with Google-hosted services, and finding they need to force e.g. cURL to add the header when there is no body.

So I suspect that api.gocardless.com has recently moved into Google's cloud and now behaves differently.

I've asked GoCardless support if they've changed anything regarding web app firewalling in front of API.

Is it still working for you, without sending a `Content-Length: 0`?

**Comment by leejo** [comment]
I'll look at our logs tomorrow and get back to you. Cheers!

**Comment by grifferz** [comment]
FYI:

> That's correct, we did move to Google Cloud earlier this year. I'm sorry that this caused an issue with your integration, but I'm glad that you managed to resolve the problem.                                                      
>                                                                                                                        
> Apologies for the lack of a heads up, unfortunately this is something that was overlooked as it seems most clients send the header through by default.
> – GoCardless Support:

**Comment by leejo** [comment]
OK, that's good enough for me. v0.32 on its way to CPAN. Thanks for catching this - we don't seem to be calling any of the methods that POST/PUT with no content so I hadn't seen it. Ta!
