### ISSUE TITLE
Package details file (cpan), missing version number

### ISSUE THREAD

**Issue by ivansifuentes** [Humanstate/business-gocardless#5]
First of all, thanks for the module it's been very helpful.

The issue is that the file containing the package details:
http://www.perl.com/CPAN/modules/02packages.details.txt

Contains "undef" as the version number, meaning an automated tool (like Carton) can't upgrade between versions.
`Business::GoCardless              undef  L/LE/LEEJO/Business-GoCardless-0.18.tar.gz`

Could you please update the cpan entry to contain the version number?

**Comment by leejo** [comment]
Think this is because the VERSION is actually in Business::GoCardless::Version and not the main package. I'll fix this tomorrow.
